import {
  LayoutDashboard,
  Search,
  Brain,
  Activity,
  Gauge,
  Zap,
  PenTool,
  Megaphone,
  Image,
  Sparkles,
  Package,
  Cog,
  Rocket,
  CalendarDays,
  Users,
  Mail,
  BarChart3,
  PlayCircle,
  FileText,
  CreditCard,
  Settings,
  Database,
  Share2,
  BookOpen,
  Flag,
  MessageCircle,
  MessageSquare,
    Eye,
    UsersRound,
} from "lucide-react";

export const APP_ROUTES = [
    {
    path: "/onboarding",
    label: "Onboarding",
    group: "workspaceCore",
    requiredPlan: null,
    gateType: null,
    hidden: true,
    tooltip: "Guided brand OS setup journey.",
  },
    {
    path: "/command-center",
    label: "Command Center",
    icon: LayoutDashboard,
    group: "workspaceCore",
    requiredPlan: "foundation",
    gateType: "page",
    tooltip:
      "Your workspace overview - brand health, journey progress, and quick access to every module.",
    lockedTooltip:
      "Unlock the Command Center on The Foundation plan.",
  },

    {
      path: "/demo-mode",
      label: "Demo Mode",
      icon: Eye,
      group: "workspaceCore",
      requiredPlan: null,
      gateType: null,
      tooltip: "Preview the Core Truth House workflow with seeded sample data.",
    },

    {
    path: "/brand-audit",
    label: "Brand Audit",
    icon: Search,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    tooltip: "Run a diagnostic across your brand and get a priority action plan.",
  },
    {
    path: "/brand-foundation",
    label: "Foundation",
    icon: BookOpen,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    tooltip:
      "Lock mission, vision, values, positioning, and the strategic architecture of the brand.",
  },
    {
    path: "/brand-positioning",
    label: "Brand Positioning",
    icon: Flag,
    group: "brandFoundation",
    requiredPlan: "foundation",
    gateType: null,
    tooltip:
      "Name your category, your specific audience, and the one thing only you do.",
  },
    {
    path: "/messaging-structure",
    label: "Messaging Structure",
    icon: MessageSquare,
    group: "brandFoundation",
    requiredPlan: "foundation",
    gateType: null,
    tooltip:
      "Turn your positioning into the brand promise, pitch, one-liner, and core message your brand speaks from.",
  },
    {
    path: "/audience",
    label: "Audience",
    icon: UsersRound,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    tooltip:
      "Define the people your brand serves and the avatars that drive every campaign.",
  },
    {
    path: "/audience/avatars/new",
    label: "Audience",
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    hidden: true,
    tooltip: "Create a new audience avatar.",
  },
    {
    path: "/audience/avatars/:id",
    label: "Audience",
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    hidden: true,
    tooltip: "Edit an audience avatar.",
  },
    {
    path: "/identity-studio",
    label: "Identity Studio",
    icon: Sparkles,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    tooltip: "Manage your visual identity system.",
  },
    {
    path: "/strategic-os",
    label: "Strategic OS",
    icon: Zap,
    group: "brandFoundation",
    requiredPlan: "foundation",
    gateType: "partial",
    tooltip:
      "The 9-step brand strategy engine - audience, positioning, content pillars, and monetization.",
    lockedTooltip:
      "Unlock the full Strategic OS on The Foundation plan. Step 1 is free to preview.",
  },
    {
    path: "/brand-memory",
    label: "Brand Memory",
    icon: Brain,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    hidden: true,
    tooltip:
      "Build the AI knowledge base that powers every downstream generation and decision.",
  },
    {
    path: "/brand-intelligence",
    label: "Brand Intelligence",
    icon: Brain,
    group: "brandFoundation",
    requiredPlan: null,
    gateType: null,
    hidden: true,
    tooltip:
      "Everything the platform knows about your brand - Brand Memory + Brand Foundation in one place.",
  },
    {
    path: "/brand-health",
    label: "Brand Health",
    icon: Activity,
    group: "brandFoundation",
    requiredPlan: "foundation",
    gateType: "page",
    hidden: true,
    tooltip:
      "Track your brand consistency score across every generated output.",
    lockedTooltip:
      "Unlock Brand Health on The Foundation plan to track consistency as you generate content.",
  },
    {
    path: "/scorecard",
    label: "Brand Health",
    icon: Activity,
    group: "brandFoundation",
    requiredPlan: "foundation",
    gateType: "page",
    hidden: true,
    tooltip:
      "Alias route for Brand Health.",
    lockedTooltip:
      "Unlock Brand Health on The Foundation plan to track consistency as you generate content.",
  },
    {
    path: "/systems-builder",
    label: "Structure",
    icon: Cog,
    group: "structure",
    requiredPlan: null,
    gateType: null,
    tooltip: "Build SOPs, workflows, and operational systems.",
  },
    {
    path: "/offer-builder",
    label: "Offers",
    icon: Package,
    group: "structure",
    requiredPlan: null,
    gateType: null,
    tooltip: "Document and structure your offers.",
  },
    {
    path: "/campaign-builder",
    label: "Campaign Builder",
    icon: Megaphone,
    group: "execution",
    requiredPlan: "foundation",
    gateType: "page",
    tooltip: "Build campaigns from your brand strategy.",
    lockedTooltip: "Unlock Campaign Builder on The Foundation plan.",
  },
    {
    path: "/campaign-setup",
    label: "Campaign Setup",
    group: "execution",
    requiredPlan: "foundation",
    gateType: "page",
    hidden: true,
    tooltip: "Create a new campaign through the three-step setup wizard.",
    lockedTooltip: "Unlock campaign creation on The Foundation plan.",
  },
  {
    path: "/community",
    label: "Cohort Community",
    icon: MessageCircle,
    group: "execution",
    requiredPlan: null,
    gateType: null,
    tooltip: "Private cohort rooms, member profiles, guided threads, and shared resources.",
  },
    {
    path: "/media-studio",
    label: "Media Studio",
    icon: Image,
    group: "execution",
    requiredPlan: null,
    gateType: null,
    tooltip: "Generate visual assets and media prompts.",
  },
    {
    path: "/content-studio",
    label: "Content Studio",
    icon: PenTool,
    group: "execution",
    requiredPlan: null,
    gateType: null,
    tooltip: "Create on-brand written content.",
  },
    {
    path: "/launch-planner",
    label: "Launch Planner",
    icon: Rocket,
    group: "execution",
    requiredPlan: "foundation",
    gateType: "page",
      hidden: true,
    tooltip: "Plan launches and rollout sequences.",
    lockedTooltip: "Unlock Launch Planner on The Foundation plan.",
  },
    {
    path: "/first-campaign",
    label: "First Campaign",
    icon: Flag,
    group: "execution",
    requiredPlan: "foundation",
    gateType: "page",
    tooltip:
      "Activate your first real campaign with a documented offer behind it.",
    lockedTooltip: "Unlock First Campaign on The Foundation plan.",
    hidden: true,
  },
    {
    path: "/social-media-manager",
    label: "Social Planner",
    icon: Share2,
    group: "insightsOps",
    requiredPlan: "foundation",
    gateType: "page",
    tooltip: "Create, schedule, and manage social content.",
    lockedTooltip: "Unlock Social Media Manager on The Foundation plan.",
  },
    {
    path: "/crm",
    label: "CRM",
    icon: Users,
    group: "insightsOps",
    requiredPlan: "structure",
    gateType: "page",
    tooltip: "Manage pipelines, lead movement, contacts, and relationship activity.",
    lockedTooltip: "Unlock CRM on The Structure plan.",
  },
  {
    path: "/mail",
    label: "Mail",
    icon: Mail,
    group: "platformAdmin",
    superAdminOnly: true,
    tooltip: "Read inbound mail, monitor click signals, manage tracking links, and ship automations.",
  },
    {
    path: "/analytics",
    label: "Analytics",
    icon: BarChart3,
    group: "insightsOps",
    requiredPlan: "foundation",
    gateType: "page",
    hidden: true,
    tooltip: "Track performance across campaigns and content.",
    lockedTooltip: "Unlock Analytics on The Foundation plan.",
  },
    {
    path: "/blog-cms",
    label: "Blog",
    icon: FileText,
    group: "insightsOps",
    requiredPlan: "foundation",
    gateType: "page",
    tooltip: "Write, manage, and publish blog content.",
    lockedTooltip: "Unlock Blog on The Foundation plan.",
  },
    {
      path: "/workspace-library",
      label: "Workspace Library",
      icon: Database,
      group: "library",
      requiredPlan: null,
      gateType: null,
      tooltip:
        "Browse the files, records, assets, content, and documents stored in your workspace.",
    },
    {
      path: "/prompt-hub",
      label: "Prompt Library",
      icon: BookOpen,
      group: "library",
      requiredPlan: null,
      gateType: null,
      tooltip:
        "Save, reuse, and manage prompts that support your brand workflows.",
    },
    {
    path: "/tutorials",
    label: "Tutorials",
    icon: PlayCircle,
    group: "help",
    requiredPlan: null,
    gateType: null,
    tooltip:
      "Step-by-step video walkthroughs for every module in the platform.",
  },
    {
    path: "/billing",
    label: "Billing",
    icon: CreditCard,
    group: "account",
    requiredPlan: null,
    gateType: null,
    tooltip:
      "Manage your plan, view credit usage, and purchase credit top-ups.",
  },
    {
    path: "/settings",
    label: "Settings",
    icon: Settings,
    group: "account",
    requiredPlan: null,
    gateType: null,
    tooltip:
      "Workspace name, display preferences, notifications, and integrations.",
  },
];

